### ISSUE TITLE
Login error on the wiki

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#197]
### What
S. O.

 Message d’erreur Wiki
“[bb8c9559ec206061c0c50dfe] /Main_Page InvalidArgumentException from line 107 of /var/www/wiki.openfoodfacts.org/extensions/AuthProductOpener/AuthProductOpener.body.php: Invalid user name
Backtrace:
#0 /var/www/wiki.openfoodfacts.org/extensions/AuthProductOpener/AuthProductOpener.body.php(65): AuthProductOpener->newSessionForRequest(array, WebRequest)
openfoodfacts/openfoodfacts-infrastructure#1 /var/www/wiki.openfoodfacts.org/includes/session/SessionManager.php(490): AuthProductOpener->provideSessionInfo(WebRequest)
openfoodfacts/openfoodfacts-infrastructure#2 /var/www/wiki.openfoodfacts.org/includes/session/SessionManager.php(215): MediaWiki\Session\SessionManager->getSessionInfoForRequest(WebRequest)
openfoodfacts/openfoodfacts-infrastructure#3 /var/www/wiki.openfoodfacts.org/includes/WebRequest.php(826): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
openfoodfacts/openfoodfacts-infrastructure#4 /var/www/wiki.openfoodfacts.org/includes/session/SessionManager.php(137): WebRequest->getSession()
openfoodfacts/openfoodfacts-infrastructure#5 /var/www/wiki.openfoodfacts.org/includes/Setup.php(725): MediaWiki\Session\SessionManager::getGlobalSession()
openfoodfacts/openfoodfacts-infrastructure#6 /var/www/wiki.openfoodfacts.org/includes/WebStart.php(89): require_once(string)
openfoodfacts/openfoodfacts-infrastructure#7 /var/www/wiki.openfoodfacts.org/index.php(44): require(string)
openfoodfacts/openfoodfacts-server#9398 {main}”

**Comment by CharlesNepote** [comment]
Won't fix. See: #543.
